[package]
name = "coin-d6"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Rafael Koch <rafael.koch@gmx.net>"]
description = "Async driver for the COIN-D6 360° spinning dToF LiDAR"
repository = "https://github.com/1-rafael-1/explorer-robot"

[lints]
workspace = true

[dependencies]
embedded-hal = "1.0.0"
embedded-io-async = "0.7.0"
libm = "0.2"

[features]
std = []

[target.'cfg(all(target_arch = "arm", target_os = "none"))'.dev-dependencies]
embassy-rp = { version = "0.10.0", features = [
    "defmt",
    "unstable-pac",
    "time-driver",
    "critical-section-impl",
    "rp235xa",
] }
embassy-executor = { version = "0.10.0", features = [
    "platform-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "defmt",
] }
embassy-time = { version = "0.5.0", features = ["defmt"] }
defmt = "1.0.1"
defmt-rtt = "1.1.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
cortex-m-rt = "0.7.5"
static_cell = "2.1.1"

[[test]]
name = "decoder"
required-features = ["std"]

[[test]]
name = "post_processing"
required-features = ["std"]

[[test]]
name = "driver"
required-features = ["std"]

