name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@1.96.0
        with:
          targets: thumbv8m.main-none-eabihf
          components: clippy

      - name: Install latest nightly rustfmt
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build"

      - name: Check formatting
        run: cargo +nightly fmt --all -- --check

      - name: Run clippy (default features)
        run: cargo clippy --target thumbv8m.main-none-eabihf -- -D warnings --no-deps

      - name: Run clippy (all features)
        run: cargo clippy --target thumbv8m.main-none-eabihf --all-features -- -D warnings --no-deps

      - name: Build
        run: cargo build --release --verbose --target thumbv8m.main-none-eabihf
