name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@1.96.0
        with:
          targets: thumbv8m.main-none-eabihf
          components: clippy

      - name: Install latest nightly rustfmt
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: true

      - name: Check formatting
        run: cargo +nightly fmt --all -- --check

      - name: Run clippy (default features)
        run: cargo clippy --workspace --target thumbv8m.main-none-eabihf --no-deps -- -D warnings

      - name: Run clippy (all features)
        run: cargo clippy --workspace --target thumbv8m.main-none-eabihf --all-features --no-deps -- -D warnings

      - name: Run clippy (examples)
        run: cargo clippy --workspace --target thumbv8m.main-none-eabihf --examples --no-deps -- -D warnings

      - name: Build
        run: cargo build --workspace --release --verbose --target thumbv8m.main-none-eabihf

      - name: Build examples
        run: cargo build --workspace --release --verbose --target thumbv8m.main-none-eabihf --examples

      - name: Test coin-d6 (host)
        run: cargo test -p coin-d6 --features std --target x86_64-unknown-linux-gnu
